modules:
  - type: rpm-ostree
    repos:
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - ansible
      - code
      - distrobox
      - gnome-tweaks
      - gparted
      - python3
      - starship
      - vim

      # Extensions
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-drive-menu

    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

