- name: Install Flatpaks
  hosts: localhost
  tasks:
  - name: Install Flatpaks
    community.general.flatpak:
      name:
        - com.discordapp.Discord
  
  - name: Remove Flatpaks
    community.general.flatpak:
      name:
        - org.gnu.emacs
      state: absent
