# image will be published to ghcr.io/<user>/<name>
name: hyprland-main
# description will be included in the image's metadata
description: The base image of GurbigggOS. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 39 # latest is also supported if you want new updates ASAP
kernel: main-39
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
                  #
                  # copies config/files/usr into your image's /usr
                  #
                  # configuration you wish to end up in /etc/ on the booted system
                  # should be added into /usr/etc/ as that is the proper "distro"
                  # config directory on ostree. Read more in the files module's README
  - type: rpm-ostree
    install: 
      - hyprland
      - hyprland-devel
  - from-file: /modules/bling.yml
  - from-file: /modules/rpms.yml
  - from-file: /modules/flatpak.yml
  - from-file: /modules/common-scripts.yml